### ISSUE TITLE
Failed to detect recipe (bittersweetblog.com)

### ISSUE THREAD

**Issue by geajack** [erik/recipecleaner#3]
When visiting this page, RecipeCleaner fails to detect the recipe (the button doesn't show in the address bar):

https://bittersweetblog.com/2016/02/23/brazilian-bread-blowout/

**Comment by erik** [comment]
Doesn't seem like this page exposes the recipe data in a structured format (either JSON-LD or microdata). Unfortunately there's not much we can do here without writing a custom scraper for the HTML on this page, which is a rabbit hole I don't really want to go down.

Thanks for reporting!
