### ISSUE TITLE
Fractions not being recognized properly as quantities

### ISSUE THREAD

**Issue by erik** [erik/recipecleaner#6]
Via feedback form:

> https://www.allrecipes.com/recipe/57028/amazingly-good-eggnog/
>
> ½ gets displayed as 5 and not as part of the highlighted quantity value. Ideally, it would be recognized as part of the quantity and the ½ character would be used directly, but if there are font problems with that then perhaps convert to 1/2. I suspect the same issue will occur with ¼ and ¾ as well.

**Comment by emdash** [comment]
This is fixed by #8
